### ISSUE TITLE
MACにunrealcv pluginを導入する時の問題点

### ISSUE THREAD

**Issue by KazumaTakata** [iory/project_dqn#9]
(MACを使う方用)
unrealcvのunreal engine pluginについてです。Binaries folderにはwindowsとlinuxの
binary fileは存在するのでそれらの環境では問題なく起動すると思いますが、MAC用のだけが存在していないので
気をつけてください。
今、コード作成者に問い合わせているところです。

しかし、pluginのコードのどこかをいじれば自分でcompileできるはずなので、詳しい方いたら教えてください。

**Comment by iory** [comment]
UnrealEngineをインストールしたところに，
UnrealEngine/EnginePluginsというdirectoryがあれば，
そこで
```
curl -L http://unrealcv.github.io/install.sh | sh
```
をやったらPluginが使えるようになったりしないかな

**Comment by KazumaTakata** [comment]
windowsとlinuxの奴はそれでできるんだけど、MACの奴だけなくて,unrealcvのissueでも問題になってるっぽい。
詳しかったら、自分でコード変えてポイポイすればいいんだろうが涙

**Comment by KazumaTakata** [comment]
コードを書いた人から返信をいただきました。
今週中に詳しい説明をホームページに書いてくれるらしいです。

**Comment by iory** [comment]
良かったです．
方針などまた話しあいましょう．
